import java.util.Random;

public class getRandom {
    public static String jr(Random random) {
        String[] jrs = {
                "Time and Space Jr",
                "Fire and Ice Jr",
                "Year Jr",
                "People Jr",
                "Mr. Jr",
                "Day Jr",
                "Man Jr",
                "Thing Jr",
                "Woman Jr",
                "Life Jr",
                "Child Jr",
                "World Jr",
                "School Jr",
                "State Jr",
                "Family Jr",
                "Student Jr",
                "Group Jr",
                "Country Jr",
                "Problem Jr",
                "Hand Jr",
                "Part Jr",
                "Place Jr",
                "Case Jr",
                "Week Jr",
                "Company Jr",
                "System Jr",
                "Program Jr",
                "Question Jr",
                "Work Jr",
                "Government Jr",
                "Number Jr",
                "Night Jr",
                "Point Jr",
                "Home Jr",
                "Water Jr",
                "Room Jr",
                "Mother Jr",
                "Area Jr",
                "Money Jr",
                "Story Jr",
                "Fact Jr",
                "Month Jr",
                "Parking lot Jr",
                "Right Jr",
                "Study Jr",
                "Book Jr",
                "Eye Jr",
                "Job Jr",
                "Word Jr",
                "Business Jr",
                "Issue Jr",
                "Side Jr",
                "Kind Jr",
                "Head Jr",
                "House Jr",
                "Service Jr",
                "Friend Jr",
                "Father Jr",
                "Power Jr",
                "Hour Jr",
                "Game Jr",
                "Line Jr",
                "End Jr",
                "Member Jr",
                "Law Jr",
                "Car Jr",
                "City Jr",
                "Community Jr",
                "Name Jr",
                "President Jr",
                "Team Jr",
                "Minute Jr",
                "Idea Jr",
                "Kid Jr",
                "Body Jr",
                "Information Jr",
                "Back Jr",
                "Parent Jr",
                "Face Jr",
                "Others Jr",
                "Level Jr",
                "Office Jr",
                "Door Jr",
                "Health Jr",
                "Person Jr",
                "Art Jr",
                "War Jr",
                "History Jr",
                "Party Jr",
                "Result Jr",
                "Change Jr",
                "Morning Jr",
                "Reason Jr",
                "Research Jr",
                "Girl Jr",
                "Guy Jr",
                "Moment Jr",
                "Movement Jr",
                "Air Jr",
                "Teacher Jr",
                "Force Jr",
                "Education Jr",
                "Backjack Jr",
                "BedTime Jr",
                "Homework Jr",
                "Bumblegorp Jr",
                "Prayer Jr",
                "Child of Christ Jr",
                "Cheese and crackers Jr",
                "javascript.Jr",
                "Youtube Jr",
                "CSGO Jr",
                "Emilio Jr",
                "Videogame Jr",
                "VC Jr",
                "Sephiroth Jr",
                "Budlight Jr",
                "Apple Sauce Jr",
                "Alfredo Jr",
                "Deez Nutz Jr",
                "Hop on one leg Jr",
                "Charleston Jr",
                "Pizza Jr",
                "Rock and a hardplace Jr",
                "Practice makes perfect Jr",
                "Fingernail Jr",
                "Baron Jr",
                "Sopping Wet Sock Jr",
                "I stepped in street milk Jr",
                "f(x) = 2x^2 + 5x + 3 Jr",
                "C:\\Program Files (x86)\\Homework Jr",
                "Benzos Jr",
                "Pavement Jr",
                "Pink Eye Jr",
                "Pepperoni Jr",
                "Jackson Peavy Jr",
                "random.nextInt(jrs.length) Jr",
                "Tyler The Jr",
                "Bookbag Jr",
                "Hearts of Iron Jr",
                "Pickle Ball Jr",
                "Squidward Jr (RIP)",
                "Simon Says Jr",
                "Light Fixture Jr",
                "Florence Darlington Technical College Jr",
                "Locked in Jr",
                "Tweaking Jr",
                "Nathan Drake Jr",
                "Walmart Jr",
                "Costco Jr",
                "Target Jr",
                "Moth Ball Jr",
                "Henny Jr",
                "Spencer J Garland Jr",
                "Discord Jr",
                "The Rot Jr",
                "Alphabet Jr",
                "Dream Jr",
                "Vision Jr",
                "Adventure Jr",
                "Wonder Jr",
                "Discovery Jr",
                "Journey Jr",
                "Exploration Jr",
                "Mystery Jr",
                "Magic Jr",
                "Fantasy Jr",
                "Quest Jr",
                "Challenge Jr",
                "Infinity Jr",
                "Universe Jr",
                "Cosmos Jr",
                "Galaxy Jr",
                "Star Jr",
                "Constellation Jr",
                "Planet Jr",
                "Moon Jr",
                "Sun Jr",
                "Astronaut Jr",
                "Rocket Jr",
                "Spacecraft Jr",
                "Alien Jr",
                "Martian Jr",
                "Moonwalker Jr",
                "Comet Jr",
                "Meteor Jr",
                "Nebula Jr",
                "Black Hole Jr",
                "Supernova Jr",
                "Solar Jr",
                "Lunar Jr",
                "Earth Jr",
                "Mars Jr",
                "Venus Jr",
                "Jupiter Jr",
                "Saturn Jr",
                "Neptune Jr",
                "Uranus Jr",
                "Pluto Jr",
                "Mercury Jr",
                "Galactic Jr",
                "Interstellar Jr",
                "Time Travel Jr",
                "Einstein Jr",
                "Newton Jr",
                "Tesla Jr",
                "Edison Jr",
                "Hawking Jr",
                "Curiosity Jr",
                "Imagination Jr",
                "Innovation Jr",
                "Creativity Jr",
                "Ingenuity Jr",
                "Bravery Jr",
                "Courage Jr",
                "Hero Jr",
                "Legend Jr",
                "Myth Jr",
                "Fable Jr",
                "Tale Jr",
                "Saga Jr",
                "Epic Jr",
                "Storyteller Jr",
                "Bard Jr",
                "Minstrel Jr",
                "Poet Jr",
                "Scribe Jr",
                "Wordsmith Jr",
                "Author Jr",
                "Writer Jr",
                "Literature Jr",
                "Library Jr",
                "Verse Jr",
                "Ballad Jr",
                "Folklore Jr",
                "Fairytale Jr",
                "Mythology Jr",
                "Explorer Jr",
                "Heroine Jr",
                "Villainess Jr",
                "Wizard Jr",
                "Sorcerer Jr",
                "Magician Jr",
                "Enchanter Jr",
                "Alchemist Jr",
                "Conjurer Jr",
                "Summoner Jr",
                "Spellcaster Jr",
                "Witch Jr",
                "Warlock Jr",
                "Druid Jr",
                "Shaman Jr",
                "Necromancer Jr",
                "Sorceress Jr",
                "Enchantress Jr",
                "Illusionist Jr",
                "Charmer Jr",
                "Potion Maker Jr",
                "Magic User Jr",
                "Sorcery Jr",
                "Witchcraft Jr",
                "Alchemy Jr",
                "Enchantment Jr",
                "Spells Jr",
                "Potions Jr",
                "Magical Jr",
                "Mystical Jr",
                "Fantastical Jr",
                "Whimsical Jr",
                "Enchanted Jr",
                "Legendary Jr",
                "Mythical Jr",
                "Mystery Jr",
                "Limerick Jr",
                "Haiku Jr",
                "Sonnet Jr",
                "Rhythm Jr",
                "Rhyme Jr",
                "Prose Jr",
                "Chapter Jr",
                "Page Jr",
                "Bookshelf Jr",
                "Adventurer Jr",
                "Heroin Jr",
                "Crack Rock Jr",
                "Acid Jr",
                "Drugs",
                "Molly Jr",
                "K Jr",
                "Fetty Jr",
                "Black Tar Heroin",
                "Chat GPT Jr",
                "Sonic Jr", 
                "Shadow Jr", 
                "Tails Jr", 
                "Knuckles Jr", 
                "Kick Jr", 
                "Punch Jr", 
                "Smack Jr", 
                "Pinch Jr", 
                "Tickle Jr", 
                "Smooch Jr", 
                "Kill Jr", 
                "Destroy Jr", 
                "Roast Jr", 
                "Broil Jr",
                "Crumple Jr", 
                "Catch Jr", 
                "Chase Jr", 
                "Hunt Jr", 
                "Deepfry Jr", 
                "Discover Jr",
                "Sneopard Sbug",
                "Broth Moth",
                "Sneopard Sbug Broth Moth",
                "Mrs. Chandler",
                "Jackson Randolph Peavy",
                "Cooper Abbot",
                "Sara Summerfield",
                "Laura Palmer",
                "Chuck Norris",
                "Audrey Pope",
                "Diego",
                "JT Dunphy",
                "Mrs. Hardee",
                "Harold Dilbourn",
                "Dr. Swinny-Carter",
                "Mr. Redfearn",
                "Aiden",
                "Super Linneen",
                "David Mark Taylor Jr",
                "Old McDonald Jr",
                "Cow Jr",
                "Piggie Jr",
                "Mark Ruffalo Jr",
                "Cheese and Crackers Jr",
                "Davis Ivey Jr",
                "Yevi Sivad Jr",
                "Jeremy Ironman Jr",
                "Lola Bunny Jr",
                "Bart Simpson Jr",
                "Roger the Alien Jr",
                "Keyboard Jr",
                "Controller Jr",
                "Melee Jr",
                "Big Scary Monster Jr",


        };
        return jrs[random.nextInt(jrs.length)];

    }

    public static String affirmation(Random random) {
        String[] Affirmations = {
                "You're cracked",
                "So goated",
                "Kratom 2024",
                "Moving different",
                "You completed that task like Tom Brady",
                "Some people call you the OJ of Telus",
                "Damn was that task JFK ?  Cause you shot that shit in the head!",
                "Campbell was here",
                "Ask Roslyn what the time is (It will be 3 hours before you expect)",
                "21",
                "drue",
                "Wait you're goated",
                "I will not join the VC until you finish the next task",
                "Mix Bud Light with Texas Pete call that a Buddy Mary",
                "Dude you just got a Shiny task!",
                "Im feeling evidence on this next one",
                "JT Dunphy got kicked out for some reason",
                "Its going to get far worse before it gets any better",
                "I 1v5'd Cole Dilsworth and his posse: https://www.youtube.com/watch?v=cfH911cHqkI&ab_channel=soup",
                "Jordan stop flexin ya muscles",
                "BANG",
                "The Joker was here",
                "Did I tell you how much I love speeding?",
                "You want to hit a bowl so bad (do it)",
                "Hey Lineen!",
                "Fire and Ice",
                "Hamburger jr?",
                "if i had one wish i would use the big red button on at all",
                "Any backjackers in the vc?",
                "we have to hack into the malware",
                "I found scientific evidence that your built different",
                "[Henry in overwatch game chat] KILL YOUR SELF",
                "[emilio out in the woods at night] \"if I saw Campbell out here I would be eating liver for dinner\"",
                "sometimes in church ill just browse the r/cracksmokers subreddit",
                "When you're prairie dogging in the vc",
                "Be the person your dog thinks killed Hitler",
                "You own the Gaza Strip",
                "Yall ever listen to 'Mongolia' by Carti?",
                "Tonights stack: 3 Kratom Beers, 400MG CBD, 5MG melatonin, 2 8-balls",
                "Emilio O'Connor",
                "Trump Mugshot: https://ichef.bbci.co.uk/news/1024/cpsprodpb/13FCD/production/_130896818_donaldtrumpfullmugshot.jpg",
                "Baller",
                "You're balling harder than time and space",
                "Balling harder than LeBron",
                "You're as goated as a goat wearing goat socks on a mountain made of goat cheese.",
                "Asheville is calling",
                "Old people are going to die soon",
                "Your the G.O.A.T of all time",
                "That task was harder than time and space",
                "I <3 stealing",
                "I <3 shoplifting",
                "I <3 hurting others",
                "I <3 completing tasks",
                "I <3 killing",
                "I <3 looting",
                "I <3 my friends",
                "I <3 Alex",
                "I <3 Linneen",
                "I <3 scamming",
                "I <3 the infinite wasteland of time and space",
                "I <3 all Telus employeees",
                "Snape is my favorite character form Harry Potter",
                "Harry Potter kinda sucks",
                "Listen to DJ Smokey",
                "40 pound bag of shake",
                "I stole $35.23 worth of product from Walmart today",
                "I love stealing more than life itself",
                "Quit and start robbing people",
                "Rick and Morty is a fire show",
                "I love Brian from family guy",
                "Roger the Alian is a funny ass guy",
                "showing my gut to hot chicks",
                "Glaze Clan",
                "saying L marriage to my parents",
                "when you a neph on the outside but you got a unc soul",
                "just dropped a band at starbucks #youngwealthy",
                "lets get a 19 year old to replace feinstein",
                "im voting for chris christie bro he has been crackin me up all day",
                "yo can i hold a few hundred bucks to build a gaming pc",
                "the USA got clapped",
                "I never respected mountan dew",
                "And on the fifth day, god said \"fuck this shit, i'm jerking off in the shower.\"",
                "Going for a 20 min walk is like watching an episode of TV called My Neighborhood",
                "Huffing krazy glue rn",
                "So fly they called pest control ",
                "Antonio brown and doja cat dating. prediction is in. ",
                "Drinking lean with John Mayer",
                "I could have been studying rn",
                "what is the dog doing",
                "The mountaints < jacking off",
                "all my woadies some goaties",
                "writing a self help book titled \"How to be Goaty\"",
                "como se dice im trynna fuck",
                "woke up feeling goaty today",
                "been seeing a lot of pictures of taylor swift at public events lately. why is she outside so much? what is she planning? #staycurious",
                "i want to start beef with my neighbor because life has been getting a little boring",
                "I KEEP THAT STEAMER ON ME LIKE A DIRTY DIAPER",
                "Everytime i see a cop I see an playstation square over the gun",
                "This line was sponsered by George Soros",
                "[Emilio] don't forget to get water ... and get High",
                "Bumblegorp",
                "I maed u a waffel!!! (^w^)>#",
                "8====D~~~~",
                "If you dont do one more task im going to kill you",
                "Nobody is gangstalking you",
                "Your family loves you",
                "You're perfect the way you are",
                "Slitherman was here",
                "I fw you",
                "Henry Smith",
                "TikTok is not that bad",
                "My hair grows really quickly",
                "I will not google symptoms today",
                "My lymph nodes are not swolen",
                "172.17.29.130",
                "I will achieve Big Boss Luxury Lifestyle",
                "Trump mugshot is not better than my selfies",
                "My dad respects art school students",
                "My life is good and full of sex",
                "I dont need drugs and alcohol to have fun",
                "My country does not hate women",
                "I am sane",
                "You're the bee's knees and the cat's pajamas",
                "I use light mode",
                "Shake X Tolerence",
                "This affirmation is sponsered by Andrew Callaghan",
                "Im Tom Brady",
                "achoo",
                "We should get some work beers later",
                "Lets order a Pizza",
                "Sweeter than pie",
                "Posted up at the family function and I have a gun",
                "Listen to Tom Brady on soundcloud",
                "ZXTRAGICCURTIS47 WAZ HERE",
                "I put the D in Drugs",
                "This affirmation is sponsered by Peter Griffin",
                ":jovial:",
                "by golly i cant get enough of this... this... say, what do ya call it again?\r\n" + //
                        "\r\n" + //
                        "\"masturbation, sir.\"\r\n" + //
                        "\r\n" + //
                        "by golly i cant get enough of this 'masturbation'!",
                "I feel like roger from american dad",
                "I'm John Stamos",
                "I'm higher than Ghandi",
                "Yo that fish over there is locked in!",
                "Yo that fish over there is tweaking!",
                "I'm going to eat a yummy cheeserburger",
                "Overwatch fucking sucks man",
                "Overwatch is fucking terrible @JacksonPeavy",
                "you can lead a horse away from heavy metals, but you can't stop it from drinking them",
                "Imagine doing K and jerking it at the beach",
                "Mexican food is goated",
                "BBW is fire",
                "Im about to go crazy on my shit",
                "Jerkin it for Jesus",
                "Where's that DAMN fourth Chaos Emerald?",
                "Don't forget to follow the Rule of Magic Twos!",
                "Make sure you use at least five FMU words in your essays, children.",
                "And now ladies and gentlemen, Mr Conway Twitty",
                "Yabba Dabba Dooooo!",
                "Praying to the Lord",
                "Jesus is my savior",
                "All and all, its just another brick in the wall",
                "We don't need no education",
                "Mother, do you think they will drop the bomb?",
                "I 3-0'ed Logan 50 billion times",
                "Pussy tastes like ketchup",
                "I killed a homeless man for food",
                "I killed a homeless man for sport",
                "Hitting my vape while I pray to Jesus",
                "I fucked a bitch and payed her with pickles",
                "Killed a dude for the meme",
                "Coffee spelled backwards is effoc",
                "Im the shit",
                "Slenderman is scared of my bitch",
                "Franks Red Hotsauce on icecream <3",
                "I'm going to fucking kill you driving crooner",
                "Pop goes the weasel"
        };
        return Affirmations[random.nextInt(Affirmations.length)];

    }

    

    // Function to get a random response from Billy Butcher
    public static String billyButcherResponse(Random random) {
        String[] BillyButcher = {
                "You did a great job, I'm proud of you!",
                "You deserve a nice bong rip after this!",
                "Wrap it up and spark that peace pipe!",
                "Time to let your hair down and blaze away!",
                "You've earned yourself a one-way ticket to relaxation station!",
                "Time to roll one up and chill like a sloth on a Sunday.",
                "You earned a break, go take a hit and watch the clouds float by, ya lazy bugger.",
                "Wrap up the day and blaze away - you've earned it, ya proper slacker.",
                "Kick back and relax, mate. Puff, puff, pass that stress away.",
                "Another day bites the dust. Time to hit the pen and mellow out.",
                "Clock out and chief down. It's high time for some relaxation.",
                "You've clocked off, now hit the Oxys and let the good vibes roll.",
                "Well done, now hit the shake and let the stress fade away like a bad memory.",
                "You've done your bit, now blaze it and forget about the day, ya weed-loving dreamer.",
                "Time to hit the hay and dream of fields of green. Goodnight, stoner.",
                "Time to hit a blinker and kick back!",
                "Crack open a cold Kratom Beer and relax, you've earned it!",
                "Kratom break, anyone?",
                "Wrap it up, it's 4:20 somewhere!",
                "If Telus had a 'Chill Mode', you'd be there, pal.",
                "Wrap it up and toss back that kratom, you herbal enthusiast.",
                "Time to call it a day and savor that kratom, 'cause reality sucks.",
                "Another day bites the dust. Grab your kratom, it's your sweet escape.",
                "Clock out and get your kratom fix. It's your ticket to la-la land, buddy.",
                "You've earned a break, now sip on that Kratom Beer and drift away.",
                "Well, well, it's quitting time. Kratom o'clock, my friend.",
                "You've done your part, now enjoy some kratom therapy.",
                "It's time to punch out and pop some kratom pills. Life's better through the haze.",
                "Wrap up the day and unwind with kratom. It's your herbal sedative, ain't it?",
                "You've hit the finish line, now hit that fucking kratom and forget the grind.",
                "You've hit the time limit, now hit that bong."
        };

        return BillyButcher[random.nextInt(BillyButcher.length)];
    }
}
